### ISSUE TITLE
Support alternative package & service name for Kibana

### ISSUE THREAD

**Issue by nick-george** [voxpupuli/puppet-kibana#16]
Hi, 

Firstly, thanks so much for finally coming out with an "Elastic" Kibana module! I'd love to start making use of the module, but can't because I rebuild Kibana from source to add additional features and name the package (& service) differently in order to de-conflict with the official release. 

Could I please request that you support alternative names for the package and service resources? 

Many thanks, 
Nick G

**Comment by tylerjl** [comment]
Sure, I think we could do that. I'll keep this feature request open for next time I (or someone else) can take a pass at adding the parameter. Cheers! 👍

**Comment by nick-george** [comment]
Awesome.. thanks!
